# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96ae7ac400849c0173004fa13ab1d310c5211d5e73d3bd24b625812306063f047a47ceea7ef5039a3a701b8114fad468aac18a51bf7ad3640afae20f44d624b

test:
  secret_key_base: 6113fab14b7ed8531177d86dff6779df69c491bf5dffc7439c53697076c66bf5cb6a80d77beef1d41f5fd8ce62fbcf8854bb73735ad6ec21680151c0f44e2b4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
